service: teste
frameworkVersion: '3'
plugins:
  - serverless-localstack
custom:
  localstack:
    host: http://127.0.0.1
    debug: true
    stages:
      - local
      - dev
provider:
  name: aws
  runtime: java11
  timeout: 15
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - s3:*
          Resource: "*"
package:
  artifact: build/libs/lambda_s3_localstack-dev-all.jar

functions:
  hello:
    handler: com.serverless.Handler
    events:
      - http:
          path: hello
          method: get
  listFile:
    handler: com.serverless.HandlerList
    events:
      - http:
          path: list-file
          method: get
  uploadFile:
    handler: com.serverless.HandlerUpload
    events:
      - http:
          path: upload-file
          method: post
  justTest:
    handler: com.serverless.JustTest
    events:
      - http:
          path: just-test
          method: get
  downloadFile:
    handler: com.serverless.HandlerDownload
    events:
      - http:
          path: download-file
          method: get